# Generated by Django 4.2.16 on 2025-01-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='home.produto'),
        ),
    ]
