# Generated by Django 4.2.16 on 2025-01-09 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_estoque_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produto'),
        ),
    ]
